<a href="https://colab.research.google.com/github/boishaki/Newcodeing/blob/main/num.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

np1=np.array ([1, 2, 3, 4])
print(np1)
print(np1.shape)
np2=np.arange(10)
print(np2)
#zeros
np3=np.zeros(10)
print(np3)

#Multidimensional full
np4 = np.full((2,10),6)
print(np4)
#convert lists to np
my_list = [1,2,3,4]
np5 = np.array(my_list)
print(np5)


[1 2 3 4]
(4,)
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]
[1 2 3 4]
